uses '../testlib', '../assert';

testsuite('Assertions') using {
	testcase('assert.is') using {
		assert('string').is('string');
		assert(100).is(100);
		assert([1,2,3]).is([1,2,3]);
	};
	
	testcase('assert.is failure') using {
		assert_error('not equal') using {
			assert('hello').is('bye');
		};
		assert_error('not equal') using {
			assert(1).is(2);
		};
		assert_error('not equal') using {
			assert([1,2,3]).is([1,2]);
		};
	};
	
	testcase('must fail') using {
		assert('hello').is(1);
	};
};
