#! /bin/bash

FERITE_ARGS=()
WATCH=0
SUMMARY_LOG=`pwd`/.test_summary

while [ $# -gt 0 ];do
	op="$1"
	shift
	case "$op" in
		-w)
			WATCH=1
			;;
		*)
			FERITE_ARGS+=("$op")
			;;
	esac
done

find_testdirs () {
	find -type d -name t -or -name test -or -name tests
}

find_files_to_monitor () {
	find -not -path '*/.*' -and -not -path '*/FarmYard*'
}

get_timestamp () {
	stat -c %Y $1
}

run_tests () {
	for x in `find_testdirs`;do
		cd $x
			for t in *;do
				ferite $t ${FERITE_ARGS[@]} 2>> $SUMMARY_LOG
			done
		cd ..
	done
	echo
	cat $SUMMARY_LOG
	rm $SUMMARY_LOG
}

run_tests

if [ $WATCH -eq 1 ];then
	if [ "`which inotifywait`" != "" ];then
		while inotifywait -q -r -e modify -e create -e delete .;do
			clear
			run_tests
		done
	else
		declare -A TIMESTAMPS
		for x in `find_files_to_monitor`;do
			TIMESTAMPS[$x]=`get_timestamp $x`
		done
		while true;do
			sleep 1
			for x in `find_files_to_monitor`;do
				t=`get_timestamp $x`
				if [ $t -ne ${TIMESTAMPS[$x]} ];then
					TIMESTAMPS[$x]=$t
					clear
					run_tests
				fi
			done
		done
	fi
fi
